export const stageSeeds = [
  // beginning
  { name: 'Big Bloom', type: 'core' },
  // micro
  { name: 'Quantum Fields', type: 'micro' },
  { name: 'Particles', type: 'micro' },
  { name: 'Atoms', type: 'micro' },
  { name: 'Molecules', type: 'micro' },
  { name: 'Biomolecules', type: 'micro' },
  { name: 'Cells', type: 'micro' },
  { name: 'Organs', type: 'micro' },
  { name: 'Us', type: 'core' }, // <-- crossover
  { name: 'Awareness', type: 'micro' },
  { name: 'Meaning', type: 'micro' },
  // end
  { name: 'Oneness', type: 'core' },
  // macro
  { name: 'Cultures', type: 'macro' },
  { name: 'Collectives', type: 'macro' },
  { name: 'Organisms', type: 'macro' },
  { name: 'Biospheres', type: 'macro' },
  { name: 'Geospheres', type: 'macro' },
  { name: 'Planets', type: 'macro' },
  { name: 'Stars', type: 'macro' },
  { name: 'Galaxies', type: 'macro' },
  { name: 'Cosmic Web', type: 'macro' },
] as const

export type StageName = typeof stageSeeds[number]['name']
export type StageType = typeof stageSeeds[number]['type']

export const stageLinks: { source: StageName; target: StageName }[] = [
  // composing
  { source: 'Big Bloom', target: 'Quantum Fields' },
  { source: 'Quantum Fields', target: 'Particles' },
  { source: 'Particles', target: 'Atoms' },
  { source: 'Atoms', target: 'Molecules' },
  { source: 'Molecules', target: 'Biomolecules' },
  { source: 'Biomolecules', target: 'Cells' },
  { source: 'Cells', target: 'Organs' },
  { source: 'Organs', target: 'Us' },
  { source: 'Us', target: 'Awareness' },
  { source: 'Awareness', target: 'Meaning' },
  { source: 'Meaning', target: 'Oneness' },
  // hosting
  { source: 'Oneness', target: 'Cultures' },
  { source: 'Cultures', target: 'Collectives' },
  { source: 'Collectives', target: 'Us' },
  { source: 'Us', target: 'Organisms' },
  { source: 'Organisms', target: 'Biospheres' },
  { source: 'Biospheres', target: 'Geospheres' },
  { source: 'Geospheres', target: 'Planets' },
  { source: 'Planets', target: 'Stars' },
  { source: 'Stars', target: 'Galaxies' },
  { source: 'Galaxies', target: 'Cosmic Web' },
  { source: 'Cosmic Web', target: 'Big Bloom' },
  // symmetry
  { source: 'Quantum Fields', target: 'Cosmic Web' },
  { source: 'Galaxies', target: 'Particles' },
  { source: 'Stars', target: 'Atoms' },
  { source: 'Planets', target: 'Molecules' },
  { source: 'Geospheres', target: 'Biomolecules' },
  { source: 'Biospheres', target: 'Cells' },
  { source: 'Organisms', target: 'Organs' },
  { source: 'Collectives', target: 'Awareness' },
  { source: 'Cultures', target: 'Meaning' },
]

export const substageSeeds: { parent: StageName; name: string }[] = [
  { parent: 'Quantum Fields', name: 'forces' },
  { parent: 'Quantum Fields', name: 'energy' },
  { parent: 'Quantum Fields', name: 'probability' },
  { parent: 'Quantum Fields', name: 'possibility' },
  { parent: 'Particles', name: 'electrons' },
  { parent: 'Particles', name: 'photons' },
  { parent: 'Particles', name: 'neutrinos' },
  { parent: 'Particles', name: 'quarks, gluons' },
  { parent: 'Atoms', name: 'nucleus' },
  { parent: 'Atoms', name: 'orbitals' },
  { parent: 'Molecules', name: 'bonds' },
  { parent: 'Molecules', name: 'reactions' },
  { parent: 'Molecules', name: 'tesselations' },
  { parent: 'Biomolecules', name: 'rna/dna' },
  { parent: 'Biomolecules', name: 'proteins' },
  { parent: 'Cells', name: 'membrane' },
  { parent: 'Cells', name: 'cytoplasm' },
  { parent: 'Cells', name: 'organelles' },
  { parent: 'Organs', name: 'envelope' },
  { parent: 'Organs', name: 'locomotion' },
  { parent: 'Organs', name: 'reproduction' },
  { parent: 'Organs', name: 'digestion' },
  { parent: 'Organs', name: 'circulation' },
  { parent: 'Organs', name: 'orchestration' },
  { parent: 'Organs', name: 'sensation' },
  { parent: 'Awareness', name: 'attention' },
  { parent: 'Awareness', name: 'causality' },
  { parent: 'Awareness', name: 'memory' },
  { parent: 'Awareness', name: 'prediction' },
  { parent: 'Meaning', name: 'abstraction' },
  { parent: 'Meaning', name: 'symbolism' },
  { parent: 'Meaning', name: 'narrative' },
  { parent: 'Meaning', name: 'naming' },
  { parent: 'Cultures', name: 'art' },
  { parent: 'Cultures', name: 'science' },
  { parent: 'Cultures', name: 'spirituality' },
  { parent: 'Cultures', name: 'politics' },
  { parent: 'Cultures', name: 'commerce' },
  { parent: 'Collectives', name: 'flocks' },
  { parent: 'Collectives', name: 'swarms' },
  { parent: 'Collectives', name: 'hives' },
  { parent: 'Organisms', name: 'animals' },
  { parent: 'Organisms', name: 'fungi' },
  { parent: 'Biospheres', name: 'plants' },
  { parent: 'Biospheres', name: 'bacteria' },
  { parent: 'Geospheres', name: 'water' },
  { parent: 'Geospheres', name: 'wind' },
  { parent: 'Geospheres', name: 'land' },
  { parent: 'Geospheres', name: 'lightning' },
  { parent: 'Geospheres', name: 'heat' },
  { parent: 'Planets', name: 'core' },
  { parent: 'Planets', name: 'crust' },
  { parent: 'Planets', name: 'oceans' },
  { parent: 'Planets', name: 'atmosphere' },
  { parent: 'Planets', name: 'magnetosphere' },
  { parent: 'Planets', name: 'moons' },
  { parent: 'Stars', name: 'fusion body' },
  { parent: 'Stars', name: 'solar wind' },
  { parent: 'Stars', name: 'heliosphere' },
  { parent: 'Stars', name: 'orbitals' },
  { parent: 'Galaxies', name: 'core' },
  { parent: 'Galaxies', name: 'disk' },
  { parent: 'Galaxies', name: 'jets' },
  { parent: 'Cosmic Web', name: 'filaments' },
  { parent: 'Cosmic Web', name: 'voids' },
]

// TODO: around "Us" -> "human" * "beings"
